# Generated by Django 5.2.17 on 2026-09-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=100, verbose_name="Место")),
                ("time", models.CharField(max_length=100, verbose_name="Время")),
                ("action", models.CharField(max_length=100, verbose_name="Действие")),
                (
                    "is_pleasure_habit",
                    models.BooleanField(
                        default=False, verbose_name="Признак приятной привычки"
                    ),
                ),
                (
                    "linked_habit",
                    models.CharField(max_length=100, verbose_name="Связанная привычка"),
                ),
                (
                    "period",
                    models.PositiveIntegerField(
                        default=0, help_text="в днях", verbose_name="Периодичность"
                    ),
                ),
                (
                    "award",
                    models.CharField(max_length=100, verbose_name="Вознаграждение"),
                ),
                (
                    "time_to_execution",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Время на выполнение"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, verbose_name="Признак приятной привычки"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LinkedHabit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
