# Generated by Django 5.2.17 on 2026-09-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="is_public",
            field=models.BooleanField(
                default=False, verbose_name="Признак публичности"
            ),
        ),
    ]
