# Generated by Django 5.2.17 on 2026-09-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker", "0003_alter_habit_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="award",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Вознаграждение"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="linked_habit",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Связанная привычка"
            ),
        ),
    ]
