# Generated by Django 5.2.17 on 2026-09-21 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker", "0004_alter_habit_award_alter_habit_linked_habit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="linked_habit",
        ),
        migrations.AddField(
            model_name="habit",
            name="linked_habit_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linked_habit",
                to="habit_tracker.habit",
            ),
        ),
    ]
