# Generated by Django 5.2.17 on 2026-09-21 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker", "0005_remove_habit_linked_habit_habit_linked_habit_1"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={"ordering": ["id"]},
        ),
    ]
