# Generated by Django 5.2.17 on 2026-09-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker", "0006_alter_habit_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="tg_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите телеграм chat-id",
                max_length=50,
                null=True,
                verbose_name="Телеграм chat-id",
            ),
        ),
    ]
