# Generated by Django 5.2.17 on 2026-09-22 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker", "0007_habit_tg_chat_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="tg_chat_id",
        ),
    ]
